apiKey: [YOUR_NEW_RELIC_API_KEY]
licenseKey: [YOUR_NEW_RELIC_LICENSE_KEY]
accountId: 123456
region: US
interval: 60
runAsService: false
pipeline:
  receiveBufferSize: 500
  harvestInterval: 60
  instances: 3
log:
  level: warn
  fileName: trace.log
databricks:
  workspaceHost: [YOUR_DATABRICKS_WORKSPACE_INSTANCE_NAME]
  accessToken: [YOUR_DATABRICKS_PERSONAL_ACCESS_TOKEN]
  oauthClientId: [YOUR_DATABRICKS_SERVICE_PRINCIPAL_OAUTH_CLIENT_ID]
  oauthClientSecret: [YOUR_DATABRICKS_SERVICE_PRINCIPAL_OAUTH_CLIENT_SECRET]
  sparkMetrics: true
  sparkMetricPrefix: spark.
  # RESERVED FOR FUTURE USE
  #accountHost: https://accounts.cloud.databricks.com
spark:
  webUiUrl: http://localhost:4040
  metricPrefix: spark.
tags:
  key1: value
  key2: value
