apiKey: [YOUR_NEW_RELIC_API_KEY]
licenseKey: [YOUR_NEW_RELIC_LICENSE_KEY]
accountId: 123456
region: US
interval: 60
runAsService: false
pipeline:
  receiveBufferSize: 500
  harvestInterval: 60
  instances: 3
log:
  level: warn
  fileName: trace.log
databricks:
  workspaceHost: [YOUR_DATABRICKS_WORKSPACE_INSTANCE_NAME]
  accountHost: [YOUR_DATABRICKS_ACCOUNTS_CONSOLE_HOST_NAME]
  accountId: [YOUR_DATABRICKS_ACCOUNT_ID]
  accessToken: [YOUR_DATABRICKS_PERSONAL_ACCESS_TOKEN]
  oauthClientId: [YOUR_DATABRICKS_SERVICE_PRINCIPAL_OAUTH_CLIENT_ID]
  oauthClientSecret: [YOUR_DATABRICKS_SERVICE_PRINCIPAL_OAUTH_CLIENT_SECRET]
  sqlStatementTimeout: 30
  spark:
    enabled: true
    metricPrefix: spark.
    clusterSources:
      ui: true
      job: true
      api: true
  usage:
    enabled: true
    warehouseId: [YOUR_DATABRICKS_WAREHOUSE_ID]
    includeIdentityMetadata: false
    runTime: 02:00:00
    optionalQueries:
      jobs_cost_list_cost_per_job_run: true
      jobs_cost_list_cost_per_job: true
      jobs_cost_frequent_failures: true
      jobs_cost_most_retries: true

spark:
  webUiUrl: http://localhost:4040
  metricPrefix: spark.
tags:
  key1: value
  key2: value
